./Turbo_C.out 0
./Turbo_C.out 1
./Turbo_C.out 2
./Turbo_C.out 3
./Turbo_C.out 4
./Turbo_SIMD.out 0
./Turbo_SIMD.out 1
./Turbo_SIMD.out 2
./Turbo_SIMD.out 3
./Turbo_SIMD.out 4
./Turbo_OMP.out 0
./Turbo_OMP.out 1
./Turbo_OMP.out 2
./Turbo_OMP.out 3
./Turbo_OMP.out 4
./Turbo_all.out 0
./Turbo_all.out 1
./Turbo_all.out 2
./Turbo_all.out 3
./Turbo_all.out 4
