#GCC PATH
GCC_DIR =

#COMPILER
CC = $(GCC_DIR)gcc
CXX = $(GCC_DIR)g++
AR = $(GCC_DIR)ar
ICC = icpc
ICCFLAGS = -O3  -std=c++0x -vec-report0 -restrict -offload=mandatory #-opt-report-phase=offload 
MMIC = -mmic
INCLUDE_DIRS += -I/opt/intel/mkl/include  -I$(HOME)/local/include/poski -I$(HOME)/local/build_oski/include/oski/  -L$(HOME)/local/lib/

ParWiBench_DIR := /home/xblee/ParWiBench
ifeq "$(ParWiBench_DIR)" ""
$(error ParWiBench project directory is not defined)
endif

LIB_DIR := $(ParWiBench_DIR)/lib
SRC_DIR := $(ParWiBench_DIR)/src

INC_FLAGS =
INC_FLAGS += -I$(LIB_DIR)

CC_DEBUG_FLAGS = -g
CXX_DEBUG_FLAGS = -g

CC_OPT_FLAGS =
#CXX_OPT_FLAGS = -O3
CXX_OPT_FLAGS = 

CCFLAGS += $(CC_DEBUG_FLAGS)
CCFLAGS += $(CC_OPT_FLAGS)
CCFLAGS += $(INC_FLAGS)

CXXFLAGS += $(CXX_DEBUG_FLAGS)
CXXFLAGS += $(CXX_OPT_FLAGS)
CXXFLAGS += $(INC_FLAGS)

ICCFLAGS += $(INC_FLAGS)

LINKFLAGS =

# OpenCL
AMD_SDK_HOME = /opt/AMDAPP
