#GCC PATH
GCC_DIR =

#COMPILER
CC = $(GCC_DIR)gcc
CXX = $(GCC_DIR)g++
AR = $(GCC_DIR)ar

WiBench_INSTALL_DIR := /home/troore/Projects/comm/HyWiBench
ifeq "$(WiBench_INSTALL_DIR)" ""
$(error WiBench Install directory is not defined)
endif

#KERNEL_DIR := $(WiBench_INSTALL_DIR)/src/kernel
MODULE_DIR := $(WiBench_INSTALL_DIR)/module
#APP_DIR := $(WiBench_INSTALL_DIR)/src/app
LTE_DIR := $(WiBench_INSTALL_DIR)/lte
#UTIL_DIR := $(WiBench_INSTALL_DIR)/src/util
UTIL_DIR := $(WiBench_INSTALL_DIR)/util
#CHANNEL_DIR := $(WiBench_INSTALL_DIR)/src/channel
#HARQ_DIR := $(WiBench_INSTALL_DIR)/src/harq

#$KERNEL_BUILD_DIR := $(WiBench_INSTALL_DIR)/build/kernel 
#APP_BUILD_DIR := $(WiBench_INSTALL_DIR)/build/app

#INC_FLAGS = -I$(WiBench_INSTALL_DIR)/src/include
INC_FLAGS = -I$(WiBench_INSTALL_DIR)/include
INC_FLAGS += -I$(UTIL_DIR)

CC_DEBUG_FLAGS = -g
CXX_DEBUG_FLAGS = -g

CC_OPT_FLAGS =
#CXX_OPT_FLAGS = -O3
CXX_OPT_FLAGS = 

CCFLAGS += $(CC_DEBUG_FLAGS)
CCFLAGS += $(CC_OPT_FLAGS)
CCFLAGS += $(INC_FLAGS)

CXXFLAGS += $(CXX_DEBUG_FLAGS)
CXXFLAGS += $(CXX_OPT_FLAGS)
CXXFLAGS += $(INC_FLAGS)

LINKFLAGS =
