#GCC PATH
GCC_DIR =

#COMPILER
CC = $(GCC_DIR)gcc
CXX = $(GCC_DIR)g++
AR = $(GCC_DIR)ar

ParWiBench_DIR := /home/troore/Projects/comm/ParWiBench
ifeq "$(ParWiBench_DIR)" ""
$(error ParWiBench project directory is not defined)
endif

LIB_DIR := $(ParWiBench_DIR)/lib
LTE_DIR := $(ParWiBench_DIR)/lte

INC_FLAGS =
INC_FLAGS += -I$(LIB_DIR)

CC_DEBUG_FLAGS = -g
CXX_DEBUG_FLAGS = -g

CC_OPT_FLAGS =
#CXX_OPT_FLAGS = -O3
CXX_OPT_FLAGS = 

CCFLAGS += $(CC_DEBUG_FLAGS)
CCFLAGS += $(CC_OPT_FLAGS)
CCFLAGS += $(INC_FLAGS)

CXXFLAGS += $(CXX_DEBUG_FLAGS)
CXXFLAGS += $(CXX_OPT_FLAGS)
CXXFLAGS += $(INC_FLAGS)

LINKFLAGS =
