./CEEQ_C.out 0
./CEEQ_C.out 1
./CEEQ_C.out 2
./CEEQ_C.out 3
./CEEQ_C.out 4
./CEEQ_SIMD.out 0
./CEEQ_SIMD.out 1
./CEEQ_SIMD.out 2
./CEEQ_SIMD.out 3
./CEEQ_SIMD.out 4
./CEEQ_OMP.out 0
./CEEQ_OMP.out 1
./CEEQ_OMP.out 2
./CEEQ_OMP.out 3
./CEEQ_OMP.out 4
./CEEQ_all.out 0
./CEEQ_all.out 1
./CEEQ_all.out 2
./CEEQ_all.out 3
./CEEQ_all.out 4
